language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script: 
  - mkdir -p build/cov  
  - php vendor/bin/phpunit
  
after_success:
  - travis_retry php vendor/bin/coveralls -v
